spring.application.name=CLOUD-APIGATEWAY
server.port=9090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=*

#spring.cloud.gateway.mvc.routes[0].id=IPLTEAM-SERVICE
#spring.cloud.gateway.mvc.routes[0].uri=lb://IPLTEAM-SERVICE
#spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/team-api/**

#spring.cloud.gateway.mvc.routes[1].id=IPLPLAYER-SERVICE
#spring.cloud.gateway.mvc.routes[1].uri=lb://IPLPLAYER-SERVICE
#spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/player-api/**

#Write  API Gateway  Route and  Predicate  info
spring.cloud.gateway.routes[0].id=IPLTEAM-SERVICE
spring.cloud.gateway.routes[0].uri=http://localhost:8081/
spring.cloud.gateway.routes[0].predicates[0]=Path=/team-api/**

spring.cloud.gateway.routes[1].id=IPLPLAYER-SERVICE
spring.cloud.gateway.routes[1].uri=http://localhost:8082/
spring.cloud.gateway.routes[1].predicates[0]=Path=/player-api/**
